version: "3.8"

services:
  rundler-pool:
    image: rundler
    command: pool
    environment:
      - RUST_LOG=debug
      - NETWORK=dev
      - NODE_HTTP=https://rpc.selendra.org
      - MIN_UNSTAKE_DELAY=2
      - PRIORITY_FEE_MODE_KIND=base_fee_percent
      - PRIORITY_FEE_MODE_VALUE=0
      - POOL_HOST=0.0.0.0

  rundler-builder:
    image: rundler
    depends_on:
      - rundler-pool
    command: builder
    environment:
      - RUST_LOG=debug
      - NETWORK=dev
      - NODE_HTTP=https://rpc.selendra.org
      - RPC_API=eth,debug
      - MIN_UNSTAKE_DELAY=2
      - DISABLE_ENTRY_POINT_V0_6=true
      - PRIORITY_FEE_MODE_KIND=base_fee_percent
      - PRIORITY_FEE_MODE_VALUE=0
      - BUILDER_PRIVATE_KEYS=0xc57ce1f4b3c390da493e6cf5d1763344fa49347a26db142c2d307eeda0293a1e,0xf349f52f154f7d3be7543ff30751e6eb6bd83622e8b23525d27cf3919b5cbfc0
      - BUILDER_POOL_URL=https://rundler-pool:50051
      - BUILDER_HOST=0.0.0.0
      - BUILDER_PORT=50051

  rundler-rpc:
    image: rundler
    depends_on:
      - rundler-builder
    ports:
      - "8080:8080"
      - "3000:3000"
    command: rpc
    environment:
      - RUST_LOG=debug
      - NETWORK=dev
      - ENTRY_POINTS=0x0000000071727De22E5E9d8BAf0edAc6f37da032
      - NODE_HTTP=https://rpc.selendra.org
      - PRIORITY_FEE_MODE_KIND=base_fee_percent
      - PRIORITY_FEE_MODE_VALUE=0
      - RPC_API=eth,debug
      - RPC_POOL_URL=https://rundler-pool:50051
      - RPC_BUILDER_URL=https://rundler-builder:50051
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 60
      start_period: 10s