development:
  chains:
    currency:
      1953: "TSEL"
      1961: "SEL"
    decimal:
      1953: 18
      1961: 18
    provider:
      1953: "https://rpc0-testnet.selendra.org"
      1961: "https://rpc0.selendra.org"
    gas_price_update_frequency_in_seconds:
      1953: 12
      1961: 12

  supported_transaction_type:
    1953:
      - "AA"
      - "SCW"
  
  relayers:
    funding_amount:
    no_of_relayers:
    max_relayer_queue_size:
  
  errors:
    nonce:

  transaction_manager:
    txn_hash_key_expiry_time:
    bump_gas_price_percentage:
      1953: 25
      1961: 25